# Generated by Django 2.1.2 on 2018-10-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IrsBusinessContact',
            fields=[
                ('business_id', models.CharField(db_column='BUSINESS_ID', max_length=9, primary_key=True, serialize=False, verbose_name='商户ID')),
                ('user_type', models.CharField(blank=True, db_column='USER_TYPE', max_length=3, null=True, verbose_name='联系人类型')),
                ('user_name', models.CharField(blank=True, db_column='USER_NAME', max_length=10, null=True, verbose_name='联系人姓名')),
                ('contact_type', models.CharField(blank=True, db_column='CONTACT_TYPE', max_length=2, null=True, verbose_name='联系方式')),
                ('contact_no', models.CharField(db_column='CONTACT_NO', max_length=30, verbose_name='微信号码')),
                ('contact_status', models.CharField(blank=True, db_column='CONTACT_STATUS', max_length=1, null=True, verbose_name='商户状态')),
                ('contype_flag', models.CharField(blank=True, db_column='CONTYPE_FLAG', max_length=1, null=True, verbose_name='通知状态')),
            ],
            options={
                'verbose_name_plural': '商户信息',
                'db_table': 'IRS_BUSINESS_CONTACT',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IrsBusinessInfo',
            fields=[
                ('business_id', models.CharField(db_column='BUSINESS_ID', max_length=9, primary_key=True, serialize=False, verbose_name='商户ID')),
                ('business_name', models.CharField(blank=True, db_column='BUSINESS_NAME', max_length=120, null=True, verbose_name='商户名称')),
                ('business_type', models.CharField(blank=True, db_column='BUSINESS_TYPE', max_length=5, null=True, verbose_name='商户类型')),
                ('business_rule', models.CharField(blank=True, db_column='BUSINESS_RULE', max_length=10, null=True, verbose_name='商户权限')),
                ('business_scope', models.CharField(blank=True, db_column='BUSINESS_SCOPE', max_length=200, null=True, verbose_name='商户经营范围')),
                ('business_address', models.CharField(blank=True, db_column='BUSINESS_ADDRESS', max_length=200, null=True, verbose_name='商户地址')),
                ('business_person', models.CharField(blank=True, db_column='BUSINESS_PERSON', max_length=10, null=True, verbose_name='负责人名称')),
                ('business_contact', models.CharField(blank=True, db_column='BUSINESS_CONTACT', max_length=11, null=True, verbose_name='商户状态')),
                ('business_status', models.CharField(blank=True, db_column='BUSINESS_STATUS', max_length=1, null=True, verbose_name='')),
                ('register_time', models.DateTimeField(blank=True, db_column='REGISTER_TIME', null=True)),
                ('register_user', models.CharField(blank=True, db_column='REGISTER_USER', max_length=10, null=True)),
                ('modify_time', models.DateTimeField(blank=True, db_column='MODIFY_TIME', null=True)),
                ('modify_user', models.CharField(blank=True, db_column='MODIFY_USER', max_length=10, null=True)),
                ('snote', models.CharField(blank=True, db_column='SNOTE', max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': '商户信息表',
                'db_table': 'IRS_BUSINESS_INFO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IrsBusinessUser',
            fields=[
                ('business_id', models.CharField(db_column='BUSINESS_ID', max_length=9, primary_key=True, serialize=False, verbose_name='商户ID')),
                ('user_type', models.CharField(blank=True, db_column='USER_TYPE', max_length=15, null=True, verbose_name='会员等级')),
                ('user_name', models.CharField(blank=True, db_column='USER_NAME', max_length=50, null=True, verbose_name='会员名称')),
                ('mobile_phone', models.CharField(blank=True, db_column='MOBILE_PHONE', max_length=11, null=True, verbose_name='手机号码')),
                ('user_wxid', models.CharField(db_column='USER_WXID', max_length=30, verbose_name='微信号码')),
                ('user_address', models.CharField(blank=True, db_column='USER_ADDRESS', max_length=200, null=True, verbose_name='联系地址')),
                ('user_status', models.CharField(blank=True, db_column='USER_STATUS', max_length=1, null=True, verbose_name='会员状态')),
                ('certificate_id', models.CharField(blank=True, db_column='CERTIFICATE_ID', max_length=18, null=True, verbose_name='身份证号')),
                ('user_birthday', models.DateField(blank=True, db_column='USER_BIRTHDAY', null=True, verbose_name='会员生日')),
                ('user_bal', models.DecimalField(blank=True, db_column='USER_BAL', decimal_places=2, max_digits=16, null=True)),
                ('user_adviser', models.CharField(blank=True, db_column='USER_ADVISER', max_length=50, null=True, verbose_name='办卡人员')),
                ('user_spread', models.CharField(blank=True, db_column='USER_SPREAD', max_length=50, null=True, verbose_name='推荐人')),
                ('register_date', models.DateField(blank=True, db_column='REGISTER_DATE', null=True, verbose_name='办卡日期')),
                ('exceed_date', models.DateField(blank=True, db_column='EXCEED_DATE', null=True, verbose_name='过期日期')),
                ('contype_flag', models.CharField(blank=True, db_column='CONTYPE_FLAG', max_length=1, null=True, verbose_name='通知状态')),
                ('snode', models.CharField(blank=True, db_column='SNODE', max_length=200, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name_plural': '商户会员表',
                'db_table': 'IRS_BUSINESS_USER',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IrsYwtyDict',
            fields=[
                ('dict_name', models.CharField(db_column='DICT_NAME', max_length=50, primary_key=True, serialize=False, verbose_name='字典名称')),
                ('dict_code', models.CharField(db_column='DICT_CODE', max_length=50, verbose_name='字典键值')),
                ('dict_target', models.CharField(blank=True, db_column='DICT_TARGET', max_length=50, null=True, verbose_name='对应解释')),
                ('dict_default', models.CharField(blank=True, db_column='DICT_DEFAULT', max_length=1, null=True, verbose_name='默认转换')),
                ('dict_snote', models.CharField(blank=True, db_column='DICT_SNOTE', max_length=200, null=True, verbose_name='字典说明')),
            ],
            options={
                'verbose_name_plural': '通用字典表',
                'db_table': 'IRS_YWTY_DICT',
                'managed': False,
            },
        ),
    ]
